apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-config-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
    - port: 6379
  selector:
    app: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: control-plane
spec:
  replicas: 1
  selector:
    matchLabels:
      app: control-plane
  template:
    metadata:
      labels:
        app: control-plane
    spec:
      containers:
        - name: control-plane
          image: your-control-plane-image:latest
          ports:
            - containerPort: 8000
          volumeMounts:
            - mountPath: /shared
              name: shared-config
      volumes:
        - name: shared-config
          persistentVolumeClaim:
            claimName: shared-config-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: control-plane
spec:
  ports:
    - port: 8000
  selector:
    app: control-plane
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidecar-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sidecar-agent
  template:
    metadata:
      labels:
        app: sidecar-agent
    spec:
      containers:
        - name: sidecar-agent
          image: your-control-plane-image:latest
          command: ["python", "-c", "import main; main.sidecar_agent()"]
          volumeMounts:
            - mountPath: /shared
              name: shared-config
      volumes:
        - name: shared-config
          persistentVolumeClaim:
            claimName: shared-config-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fake-app
  template:
    metadata:
      labels:
        app: fake-app
    spec:
      containers:
        - name: fake-app
          image: your-control-plane-image:latest
          command: ["python", "-c", "import main; main.fake_application()"]
          volumeMounts:
            - mountPath: /shared
              name: shared-config
      volumes:
        - name: shared-config
          persistentVolumeClaim:
            claimName: shared-config-pvc